opposite_of_progress/good_deeds_feed/config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'

  get 'favorites/destroy'

  get 'good_deeds/index'

  get 'good_deeds/show'

  get 'legislators/index'

  get 'legislators/show'

  get 'bills/index'

  get 'bills/show'

  get 'sessions/new'

  root 'good_deeds#index'

  get 'users/new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'legislators_by_party' => 'legislators#by_party'
  get 'good_deeds_by_party' => 'good_deeds#by_party'
  get 'good_deeds_json_feed' => 'good_deeds#json_feed'
  resources :legislators
  resources :good_deeds
  resources :users
  resources :favorites, only: [:create, :destroy]
end

opposite_of_progress/good_deeds_feed/app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :legislator
  validates :legislator_id, presence: true, uniqueness: { scope: :user_id }
  validates :user_id, presence: true
end

opposite_of_progress/good_deeds_feed/app/models/good_deed.rb
class GoodDeed < ActiveRecord::Base
  after_create :send_email_notification

  belongs_to :legislator
  default_scope -> { order(introduced_on: :desc) }
  scope :to_json, -> { all.to_json }
  validates :congress_number, presence: true
  validates :congress_url, presence: true, uniqueness: { case_sensitive: false }
  validates :short_title, presence: true, uniqueness: { case_sensitive: false }
  validates :official_title,  presence: true,
                              uniqueness: { case_sensitive: false }
  validates :introduced_on, presence: true
  validates :legislator_id, presence: true

  def self.by_party(party)
    joins(:legislator).where(legislators: { party: party })
  end

  def send_email_notification
    GoodDeedsMailer.new_deed_notification(self).deliver
  end
end

opposite_of_progress/good_deeds_feed/app/models/legislator.rb
class Legislator < ActiveRecord::Base
  has_many :good_deeds
  has_many :favorites
  has_many :users, through: :favorites
  default_scope -> { order(lastname: :asc) }
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :bioguide_id, presence: true, uniqueness: { case_sensitive: false }
  validates :party, presence: true
  validates :state, presence: true
  validates :birthdate, presence: true
end

opposite_of_progress/good_deeds_feed/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  has_many :favorites
  has_many :legislators, through: :favorites
  has_many :good_deeds, through: :legislators

  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def favorite_legislator(legislator)
    legislators << legislator unless following_legislator?(legislator)
  end

  def following_legislator?(legislator)
    legislators.include?(legislator)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

opposite_of_progress/good_deeds_feed/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :logged_in_user

  def create
    unless current_user.following_legislator?(Legislator.find(params[:id]))
      legislator = Legislator.find(params[:id])
      current_user.favorite_legislator(legislator)
    end
    redirect_to user_url(current_user)
  end

  def destroy
    if current_user.favorites.exists?(id: params[:id])
      current_user.favorites.find(params[:id]).destroy
      flash[:success] = "Favorite removed"
    end
    redirect_to user_url(current_user)
  end

  private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger].now = "Please log in."
      redirect_to login_url
    end
  end
end

opposite_of_progress/good_deeds_feed/app/controllers/good_deeds_controller.rb
class GoodDeedsController < ApplicationController
  def index
    @good_deeds = GoodDeed.order(:legislator_id).paginate(page: params[:page])
  end

  def show
    @good_deed = GoodDeed.find(params[:id])
  end

  def by_party
    @good_deeds = GoodDeed.by_party(params[:party]).
                    paginate(page: params[:page])
    render :index
  end

  def json_feed
    @json_deeds = GoodDeed.to_json
    render json: @json_deeds
  end
end

opposite_of_progress/good_deeds_feed/app/controllers/legislators_controller.rb
class LegislatorsController < ApplicationController
  def index
    @legislators = Legislator.paginate(page: params[:page])
  end

  def by_party
    @legislators = Legislator.where(party: params[:party]).
                    paginate(page: params[:page])
    render :index
  end

  def show
    @legislator = Legislator.find(params[:id])
    @good_deeds = @legislator.good_deeds.paginate(page: params[:page])
  end
end

opposite_of_progress/good_deeds_feed/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_path
  end
end

opposite_of_progress/good_deeds_feed/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @favorites = @user.favorites.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Success! #yolo"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

opposite_of_progress/good_deeds_feed/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
  end

  def remember(user)
    user.remember
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

opposite_of_progress/good_deeds_feed/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "good deeds feed", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Legislators", legislators_path %></li>
        <li><%= link_to "Good Deeds", good_deeds_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

opposite_of_progress/good_deeds_feed/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%=  render 'layouts/header' %>
    <div class="container">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

opposite_of_progress/good_deeds_feed/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

opposite_of_progress/good_deeds_feed/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

opposite_of_progress/good_deeds_feed/app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <p><%= @user.name %></p>
        <p><%= @user.email %></p>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
      <h3>Recent good deeds sponsored by your favorite legislators</h3>
  <% @user.good_deeds.all.order(:introduced_on).limit(5).each do |good_deed| %>
      <ol class="good_deeds">
        <%= render good_deed %>
      </ol>
    <% end %>

      <h3>Favorite Legislators (<%= @user.favorites.count %>)</h3>
      <ol class="favorites">
          <%= render @user.favorites %>
      </ol>
  </div>
</div>