cyoa/event_aggregator/config/routes.rb
Rails.application.routes.draw do
  resources :event_sources
  resources :events
 
  get "/feeds", to: redirect("/my-feeds")
   
  resources :feeds do
    resources :selection_criteria
    resources :event_sources, only: :index
  end

  root to: "site#home"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  } 

  devise_scope :user do
    get "/users/sign_out", to: "users/sessions#destroy"
  end

  get "/about-us", to: "site#about_us", as: :about_us
  get "/contact-us", to: "site#contact_us", as: :contact_us
  get "/privacy-policy", to: "site#privacy_policy", as: :privacy_policy
  get "/terms-and-conditions", 
      to: "site#terms_and_conditions", as: :terms_and_conditions
  get "/my-feeds", to: "feeds#index", as: :my_feeds
end

cyoa/event_aggregator/app/controllers/site_controller.rb
class SiteController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @highlight_events = highlight_events
    @meetups = meetups
    @opening_night_events = opening_night_events
  end

  private

  def highlight_events
    random_events(4)
  end

  def meetups
    random_events(2)
  end

  def opening_night_events
    random_events(2)
  end

  def random_events(count)
    CalendarEvent.select(:family_hash).distinct.sample(count).map do |event|
      CalendarEvent.find_by(family_hash: event[:family_hash])
    end
  end
end

cyoa/event_aggregator/app/helpers/site_helper.rb
module SiteHelper
end

cyoa/event_aggregator/app/views/site/_event_highlight.erb
<div class="event-highlight thumbnail"> 
  <h4><%= event.title %></h4>
  <img class="event-image" src="<%= event.image_url || image_path("calendar.svg")%>">
  <div class="caption">
    <h5>Description</h5>
    <p><%= event.description %></p>
  </div>
</div>

cyoa/event_aggregator/app/views/site/_feed_highlight.erb
<div class="feed-highlight">
<% if defined? feed_title %>
<h2 class="feed-highlight-title"><%= feed_title %></h2>
<% end %>
  <div class="row">
<%
count ||= events.count
col_width ||= [12 / count, 2].max.to_i
col_class = "col-xs-#{col_width}"
events[0, count].each do |event| %>
      <div class="<%= col_class %> feed-event-highlight">
  <%= render partial: "event_highlight", locals: { event: event } %>
      </div>
<% end %>
  </div>
</div>

cyoa/event_aggregator/app/views/site/about_us.html.erb
<h1 id="AboutUsTitle">About Us</h1>

<div class="section">
<h2 class="section-title">Who Are We?</h2>

We are somebody.

</div>
<div class="section">
<h2 class="section-title">Why Are We Here?</h2>

Because you want us to be.

</div>
<div class="section">
<h2 class="section-title">Who Are You?</h2>

You are our best friend.

</div>
<div class="section">
<h2 class="section-title">What To Do?</h2>

Use this stuff.

</div>
<div class="section">
<h2 class="section-title">About Privacy</h2>

Pffft! Well, if you really want to know, 
<%= link_to "read this.", privacy_policy_path %>

</div>
<div class="section">
<h2 class="section-title">Terms and Conditions</h2>

<%= link_to "Please don't read this", terms_and_conditions_path %>
</div>

cyoa/event_aggregator/app/views/site/contact_us.html.erb
<%
  telno = EventAggregator.customer_service_telno
  email = EventAggregator.customer_service_email
  address = EventAggregator.customer_service_mail
%>
<div id="ContactUs" class="">
  <h1><span class="hard-to-see">Don't</span><br />Contact Us</h1>

  <div id="CallUs" class="section">
    <div class="section-title">
      <h2><span class="hard-to-see">Don't </span>Call Us</h2>
    </div>

    <p>Customer service (satisfied customers only, please): 
      <a href="tel:<%= telno %>"><%= telno %></a></p>
  </div>
  <div id="EmailUs" class="section">
    <div class="section-title">
      <h2><span class="hard-to-see">Don't </span>E-Mail Us</h2>
    </div>

    <p>Send your inquiries to: <a href="mailto:<%= email %>">
      Customer Service Elf People &lt;<%= email %>&gt;</a></p>
  </div>
  <div id="MailUs" class="section">
    <div class="section-title">
      <h2><span class="hard-to-see">Don't </span>Send Us Mail</h2>
    </div>

    <p>To sue us or serve process, send mail to 
      <span class="anunciated">
          <%= link_to "(But please see our Terms and Conditions):",
                      terms_and_conditions_path %></span></p>

    <div id="CompanyAddress" class="mail-address">
      <% address.each do |line| %>
        <p class="address_line"><%= line %></p>
      <% end %>
    </div>
  </div>
</div>

cyoa/event_aggregator/app/views/site/home.html.erb
<div id="ChicagoHighlights" class="section">
<h1 class="section-title">Chicago Highlights</h1>
<%= 
render partial: 'feed_highlight',
       locals: { events: @highlight_events }
%>
</div>
<div id="HotTopics" class="section">
<h1 class="section-title">Hot Topics</h1>
<div class="row">
  <div class="col-xs-6">
<%=
render partial: 'feed_highlight',
       locals: {
         feed_title: 'Opening Night Calendar',
         events: @opening_night_events,
         count: 2,
       }
%>
  </div>
  <div class="col-xs-6">
<%=
render partial: 'feed_highlight',
       locals: {
         feed_title: "Meetups",
         events: @meetups,
         count: 2,
       }
%>
  </div>
</div>

cyoa/event_aggregator/app/views/site/privacy_policy.html.erb
<div id="PrivacyPolicy" class="jumbotron section">
<h3 class="section-title">Our Privacy Policy</h1>
We promise to make ambiguous unenforceable claims to care about the privacy of
your personal information, and to safeguard it from unauthorized access to the
fullest extent possible without doing anything. We take your perception
of privacy very seriously, and we're committed to giving you full confidence in
your security no matter what we have to say.  We encourage you feel comfortable
ignoring the issue further for maximum enjoyment of our site experience. It is
customary stop reading this Policy here because it bores
you and you lack sufficient knowledge to understand the full risk and
consequence of exposure through this site, so you are too ignorant to feel the
proper need for due caution. We thank you for putting your trust in us, and -
oh, look at the silly monkey! - Have a nice day!
</div>

cyoa/event_aggregator/app/views/site/terms_and_conditions.html.erb
<h1>Terms Of Use</h1>
<div class="jumbotron">
If your use of this site brings devastation to your world, complete or in part,
then We are indemnified from your condemnation. We told you so. So don't say we
never told you so. Use of this site for any purpose is strictly prohibited.
Don't do it. We're watching you, bud. Except if something bad happens, in which
case, we weren't watching and there's no phreaking way we could have ever known.
You have been warned. Again. Now go away. Why are you still here?
</div>