opposite_of_progress/congress/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "deeds#index"
  get 'home' => "deeds#index"

  get 'preferences' => "users#preferences"
  post 'preferences' => "users#update"

  resources :bills
  resources :legislators
  resources :deeds
end

opposite_of_progress/congress/app/models/bill.rb
# Base Bill class
class Bill < ActiveRecord::Base
  scope :by_sponsor_id, ->(id) { where(sponsor_id: id) }
  scope :all_sorted, ->(page, sort_by) { order(sort_by).paginate(page: page) }

  def title
    short_title || bill_id
  end

  def self.from_api_result(result)
    {
      bill_id: result['bill_id'],
      bill_type: result['bill_type'],
      number: result['number'],
      congress: result['congress'],
      chamber: result['chamber'],
      introduced_on: result['introduced_on'],
      last_action_at: result['last_action_at'],
      last_vote_at: result['last_vote_at'],
      last_version_on: result['last_version_on'],
      official_title: result['official_title'],
      short_title: result['short_title'],
      sponsor_id: result['sponsor_id'],
      enacted_on: result['history']['enacted_on'],
    }
  end
end

opposite_of_progress/congress/app/models/deed.rb
class Deed < ActiveRecord::Base
  scope :all_sorted, ->(page, sort_by) { order(sort_by).paginate(page: page) }
  scope :related_bill, ->(deed) { where(bioguide_id: deed.bioguide_id).first }

  def self.all_related(deed)
    Deed.where('id != ? and (bioguide_id = ? or bill_id = ?)',
               deed.id, deed.bioguide_id, deed.bill_id)
  end
end

opposite_of_progress/congress/app/models/legislator.rb
# Base Legislator class
class Legislator < ActiveRecord::Base
  scope :by_bioguide_id, ->(id) { where(bioguide_id: id).first }
  scope :all_sorted, ->(page, sort_by) { order(sort_by).paginate(page: page) }

  def full_name
    [title, first_name, nickname, last_name, display_party].compact.join(" ")
  end

  def display_party
    "(#{party})" if party
  end

  def full_party
    case party
      when "R" then "Republican"
      when "D" then "Democrat"
      when "I" then "Independent"
      when "G" then "Green"
      else "Politician"
    end
  end

  def self.from_api_result(result)
    {
      bioguide_id: result['bioguide_id'],
      birthday: result['birthday'],
      chamber: result['chamber'],
      party: result['party'],
      title: result['title'],
      term_start: result['term_start'],
      term_end: result['term_end'],
      gender: result['gender'],
      first_name: result['first_name'],
      nickname: result['nickname'],
      middle_name: result['middle_name'],
      last_name: result['last_name'],
      state: result['state'],
      twitter_id: result['twitter_id'],
      facebook_id: result['facebook_id'],
      phone: result['phone'],
      website: result['website'],
      office: result['office'],
      contact_form: result['contact_form'],
    }
  end
end

opposite_of_progress/congress/app/models/user.rb
# Base User class
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
end

opposite_of_progress/congress/app/controllers/application_controller.rb
# Application controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

opposite_of_progress/congress/app/controllers/bills_controller.rb
# Bills controller
class BillsController < ApplicationController
  before_action :set_bill, only: [:show]

  def index
    @results = Bill.all_sorted(params[:page], params[:sort_by])
  end

  def show
    @legislator = Legislator.by_bioguide_id(@bill.sponsor_id)
  end

  private

  def set_bill
    @bill = Bill.find(params[:id])
  end
end

opposite_of_progress/congress/app/controllers/deeds_controller.rb
# Deeds controller
class DeedsController < ApplicationController
  before_action :set_deed, only: [:show]

  def index
    @results = Deed.all_sorted(params[:page], "occurrence_date DESC")
  end

  def show
    @legislator = Legislator.where(bioguide_id: @deed.bioguide_id).first
    @bill = Bill.where(bill_id: @deed.bill_id).first
    @related_deeds = Deed.all_related(@deed)
  end

  private

  def set_deed
    @deed = Deed.find(params[:id])
  end
end

opposite_of_progress/congress/app/controllers/legislators_controller.rb
# Legislators controller
class LegislatorsController < ApplicationController
  before_action :set_legislator, only: [:show]

  def index
    @results = Legislator.all_sorted(params[:page], params[:sort_by])
  end

  def show
    @related_bills = Bill.by_sponsor_id(@legislator.bioguide_id)
  end

  private

  def set_legislator
    @legislator = Legislator.find(params[:id])
  end
end

opposite_of_progress/congress/app/helpers/application_helper.rb
# Application helper module
module ApplicationHelper
  def self.date_display(date)
    date.strftime("%B %d %Y") if date
  end
end

opposite_of_progress/congress/app/helpers/bills_helper.rb
# Bills helper module
module BillsHelper
  def self.sort_options
    [["Newly Added", "created_at"],
     ["Congress", "congress"],
     ["Introduction Date", "introduced_on"],
     ["Title", "short_title"]]
  end
end

opposite_of_progress/congress/app/helpers/deeds_helper.rb
# Deeds helper module
module DeedsHelper
  def self.law_voted_on
    Bill.order(:updated_at).all.each do |bill|
      if bill.last_vote_at && bill.short_title
        deed_text = "#{bill.short_title} was last voted on " \
          "#{ApplicationHelper.date_display(bill.last_vote_at)}"

        DeedsHelper.deed_creator bill, "last_vote_at", deed_text
      end
    end
  end

  def self.enacted_into_law
    Bill.order(:updated_at).all.each do |bill|
      if bill.congress == 113 && bill.enacted_on && bill.short_title
        deed_text = "#{bill.short_title} was enacted on " \
          "#{ApplicationHelper.date_display(bill.enacted_on)}"

        DeedsHelper.deed_creator bill, "enacted_on", deed_text
      end
    end
  end

  def self.deed_creator(bill, bill_date_field, deed_text)
    deed = Deed.find_or_create_by(bill_id: bill.bill_id,
                                  bioguide_id: bill.sponsor_id,
                                  deed: deed_text,
                                  occurrence_date: bill[bill_date_field])
    deed.save
  end

  def self.related_legislator(deed)
    Legislator.where(bioguide_id: deed.bioguide_id).first
  end

  def self.related_bill(deed)
    Bill.where(bill_id: deed.bill_id).first
  end
end

opposite_of_progress/congress/app/helpers/legislators_helper.rb
# Legislators helper module
module LegislatorsHelper
  def self.sort_options
    [["Newly Added", "created_at"],
     ["Term Start", "term_start"],
     ["Last Name", "last_name"],
     ["First Name", "first_name"]]
  end
end

opposite_of_progress/congress/app/views/deeds/_deed_list_item.html.erb
<div class="panel">
  <h4><%= raw "#{link_to deed_list_item.deed, deed_list_item}" %></h4>
  
  <div class="row">
    <div class="large-6 columns">
      <% if deed_list_item.bioguide_id %>
        <% legislator = DeedsHelper.related_legislator deed_list_item %>
        <%= render partial: "legislators/legislator", locals: {legislator: legislator, deed: deed_list_item} %>
      <% end %>
    </div>
    <div class="large-6 columns">
      <% if deed_list_item.bill_id %>
        <% bill = DeedsHelper.related_bill deed_list_item %>
        <%= render bill %>
      <% end %>
    </div>
  </div>
</div>

opposite_of_progress/congress/app/views/deeds/_deed_stub_item.html.erb
<div class="panel">
  <h5>
    <%= "Deed:" %>
    <% title = deed.deed %>
    <%= raw "#{link_to title, deed}" if title %>
  </h5>
  <p class="supporting-date">Date: <%= ApplicationHelper.date_display(deed.occurrence_date) %></p>
</div>

opposite_of_progress/congress/app/views/deeds/index.html.erb
<h3>All Good Deeds</h3>

<%= render partial: "deed_list_item", collection: @results %>
<%= "There are no good deeds to show" if @results.count == 0 %>

<hr />

<div class="pagination"><%= will_paginate @results %></div>

opposite_of_progress/congress/app/views/deeds/show.html.erb
<h3><%= @deed.deed %></h3>

<hr />

<h4>Basics</h4>
<blockquote>
  <%= render partial: "layouts/generic_object_details", locals: {object: @deed} %>
</blockquote>

<h4>Legislator</h4>
<blockquote>
  <%= render partial: "legislators/legislator", locals: {legislator: @legislator, deed: @deed} %>
</blockquote>

<h4>Bill</h4>
<blockquote>
  <%= render @bill %>
</blockquote>

<h4>Related Deeds</h4>
<blockquote>
  <% @related_deeds.each do |deed| %>
    <%= render partial: "deeds/deed_stub_item", locals: {deed: deed} %>
  <% end %>
  <%= "There are no related deeds" if @related_deeds.count == 0 %>
</blockquote>

<hr />

<p class="back_link"><%= link_to "Back to Good Deeds", deeds_path %></p>